<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>CfGen</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\GraamFlows.Core\GraamFlows.Core.csproj" />
        <ProjectReference Include="..\..\src\GraamFlows.Domain\GraamFlows.Domain.csproj" />
        <ProjectReference Include="..\..\src\GraamFlows.Objects\GraamFlows.Objects.csproj" />
        <ProjectReference Include="..\..\src\GraamFlows.Util\GraamFlows.Util.csproj" />
    </ItemGroup>
</Project>
